name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt update
          apt install -y debhelper libaccountsservice-dev libglib2.0-dev libgranite-7-dev libgtk-4-dev libadwaita-1-dev libpolkit-gobject-1-dev libswitchboard-3-dev libdbus-1-dev policykit-1 libflatpak-dev libmalcontent-0-dev systemd meson valac
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: elementary/actions/vala-lint@master
