name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          apt update
          apt install -y debhelper libaccountsservice-dev libglib2.0-dev libgranite-dev libgtk-3-dev libhandy-1-dev libpolkit-gobject-1-dev libswitchboard-2.0-dev libdbus-1-dev policykit-1 libflatpak-dev libmalcontent-0-dev systemd meson valac
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: elementary/actions/vala-lint@master
